import { ICard, IClass, IType } from '../interface';

export const defaultDeck: Array<ICard> = [
	{
		id: 1,
		name: 'Classe',
		description: 'descrição de paladino',
		attack: 5,
		def: 7,
		type: 'Magia',
		mana: 10,
		class: 'Paladino',
		image: 'src/assets/images/paladin.png',
		color: '#ffd700',
	},
	{
		id: 2,
		name: 'Classe',
		description: 'descrição de paladino',
		attack: 5,
		def: 7,
		type: 'Magia',
		mana: 10,
		class: 'Paladino',
		image: '//imgur.com/F8aJBgg',
		color: '#ffd700',
	},
	{
		id: 3,
		name: 'Classe',
		description: 'descrição de Mago',
		attack: 8,
		def: 2,
		type: 'Magia',
		mana: 10,
		class: 'Mago',
		image: '//imgur.com/2Kush7b',
		color: '#4169e1',
	},
	{
		id: 4,
		name: 'Classe',
		description: 'descrição de Mago',
		attack: 7,
		def: 3,
		type: 'Magia',
		mana: 10,
		class: 'Mago',
		image: '//imgur.com/2Kush7b',
		color: '#4169e1',
	},
	{
		id: 5,
		name: 'Classe',
		description: 'descrição de Caçador',
		attack: 6,
		def: 3,
		type: 'Magia',
		mana: 10,
		class: 'Caçador',
		image: '//imgur.com/a/7bpa3zV',
		color: '#8b4513',
	},
	{
		id: 6,
		name: 'Classe',
		description: 'descrição de Caçador',
		attack: 7,
		def: 3,
		type: 'Magia',
		mana: 10,
		class: 'Caçador',
		image: '//imgur.com/a/7bpa3zV',
		color: '#8b4513',
	},
	{
		id: 7,
		name: 'Classe',
		description: 'descrição de Druida',
		attack: 6,
		def: 3,
		type: 'Magia',
		mana: 10,
		class: 'Druida',
		image: '//imgur.com/a/FAdt3rT',
		color: '#228b22',
	},
	{
		id: 8,
		name: 'Classe',
		description: 'descrição de Druida',
		attack: 7,
		def: 3,
		type: 'Magia',
		mana: 10,
		class: 'Druida',
		image: '//imgur.com/a/FAdt3rT',
		color: '#228b22',
	},
	{
		id: 9,
		name: 'Criatura',
		description: 'descrição de Criatura',
		attack: 6,
		def: 3,
		type: 'Magia',
		mana: 10,
		class: 'Qualquer',
		image: '',
		color: '#8e9598',
	},
	{
		id: 10,
		name: 'Criatura',
		description: 'descrição de Criatura',
		attack: 7,
		def: 3,
		type: 'Magia',
		mana: 10,
		class: 'Qualquer',
		image: '',
		color: '#8e9598',
	},
];

export const Type: Array<IType> = [
	{
		id: '0',
		value: '',
		label: '',
	},
	{
		id: '1',
		value: 'Magia',
		label: 'Magia',
	},
	{
		id: '2',
		value: 'Criatura',
		label: 'Criatura',
	},
];
export const Class: Array<IClass> = [
	{
		value: '',
		label: '',
		id: '#383838',
	},
	{
		value: 'Mago',
		label: 'Mago',
		id: '#4169e1',
	},
	{
		value: 'Paladino',
		label: 'Paladino',
		id: '#ffd700',
	},
	{
		value: 'Caçador',
		label: 'Caçador',
		id: '#8b4513',
	},
	{
		value: 'Druida',
		label: 'Druida',
		id: '#228b22',
	},
	{
		value: 'Qualquer',
		label: 'Qualquer',
		id: '#8e9598',
	},
];
